##
## Makefile for MiniLibX in /home/boulon/work/c/raytraceur/minilibx
## 
## Made by Olivier Crouzet
## Login   <ol@epitech.net>
## 
## Started on  Tue Oct  5 15:56:43 2004 Olivier Crouzet
## Last update Tue May 15 15:44:41 2007 Olivier Crouzet
##

## Please use configure script
SHELL	=	/bin/bash

ERASE	= \033[2K\r
BLUE	= \033[36m
WHITE	= \033[37m
END		= \033[0m
GREEN	= \033[0;32m
RED		= \033[0;31m
YELLOW	= \033[0;33m

all	: do_configure

do_configure	:
	@./configure
	@printf "$(ERASE)->  $(GREEN)MiniLibX$(WHITE): OK$(END)\n"

clean	:
	@./configure clean

fclean : clean

re	: clean all
